GO
USE master
GO
DROP DATABASE IF EXISTS  UniDloX
GO
CREATE DATABASE UniDloX
GO
USE UniDloX
GO

CREATE TABLE [StaffHired](
	SHID CHAR(5) PRIMARY KEY CHECK(SHID LIKE 'SF[0-9][0-9][0-9]'),
	SHName VARCHAR(100) NOT NULL,
	SHPhoneNum VARCHAR(20) NOT NULL,
	SHAddress VARCHAR(100) NOT NULL CHECK(LEN(SHAddress) BETWEEN 10 AND 15),
	SHAge INT NOT NULL,
	SHGender VARCHAR(20) NOT NULL CHECK(SHGender IN('Male', 'Female')),
	SHSalary INT NOT NULL,
	SHDOB DATE NOT NULL
);

CREATE TABLE [Supplier](
	SupID CHAR(5) PRIMARY KEY CHECK(SupID LIKE 'SU[0-9][0-9][0-9]'),
	SupName VARCHAR(100) NOT NULL CHECK(LEN(SupName) > 6),
	SupPhoneNum VARCHAR(20) NOT NULL,
	SupAddress VARCHAR(100) NOT NULL
);

CREATE TABLE [Customer](
	CustID CHAR(5) PRIMARY KEY CHECK(CustID LIKE 'CU[0-9][0-9][0-9]'),
	CustName VARCHAR(100) NOT NULL,
	CustPhoneNum VARCHAR(20) NOT NULL,
	CustAddress VARCHAR(100) NOT NULL,
	CustGender VARCHAR(20) NOT NULL CHECK(CustGender IN('Male', 'Female')),
	CustEmail VARCHAR(50) NOT NULL CHECK(RIGHT(CustEmail, 10) IN('@gmail.com', '@yahoo.com')),
	CustDOB DATE NOT NULL
);

CREATE TABLE [PaymentType](
	PaymentTypeID CHAR(5) PRIMARY KEY CHECK(PaymentTypeID LIKE 'PA[0-9][0-9][0-9]'),
	PaymentTypeName VARCHAR(100) NOT NULL
);

CREATE TABLE [PurchaseTransactionHeader](
	PTID CHAR(5) PRIMARY KEY CHECK(PTID LIKE 'PU[0-9][0-9][0-9]'),
	SHID CHAR(5) FOREIGN KEY REFERENCES [StaffHired]([SHID]) ON UPDATE CASCADE ON DELETE CASCADE,
	SupID CHAR(5) FOREIGN KEY REFERENCES [Supplier]([SupID]) ON UPDATE CASCADE ON DELETE CASCADE,
	PaymentTypeID CHAR(5) FOREIGN KEY REFERENCES [PaymentType]([PaymentTypeID]) ON UPDATE CASCADE ON DELETE CASCADE,
	TransactionDate DATE
);

CREATE TABLE [MaterialPurchased](
	MatPurchaseID CHAR(5) PRIMARY KEY CHECK(MatPurchaseID LIKE 'MA[0-9][0-9][0-9]'),
	MatName VARCHAR(100) NOT NULL,
	MatPrice INT NOT NULL CHECK(MatPrice > 0)
);


CREATE TABLE [PurchaseTransactionDetail](
	PTID CHAR(5) FOREIGN KEY REFERENCES [PurchaseTransactionHeader]([PTID]) ON UPDATE CASCADE ON DELETE CASCADE,
	MatPurchaseID CHAR(5) FOREIGN KEY REFERENCES [MaterialPurchased]([MatPurchaseID]) ON UPDATE CASCADE ON DELETE CASCADE,
	Quantity INT,
	PRIMARY KEY([PTID], [MatPurchaseID])
);

CREATE TABLE [SalesTransactionHeader](
	STID CHAR(5) PRIMARY KEY CHECK(STID LIKE 'SA[0-9][0-9][0-9]'),
	SHID CHAR(5) FOREIGN KEY REFERENCES [StaffHired]([SHID]) ON UPDATE CASCADE ON DELETE CASCADE,
	CustID CHAR(5) FOREIGN KEY REFERENCES [Customer]([CustID]) ON UPDATE CASCADE ON DELETE CASCADE,
	PaymentTypeID CHAR(5) FOREIGN KEY REFERENCES [PaymentType]([PaymentTypeID]) ON UPDATE CASCADE ON DELETE CASCADE,
	TransactionDate DATE
);

CREATE TABLE [ClothSold](
	ClothSoldID CHAR(5) PRIMARY KEY CHECK(ClothSoldID LIKE 'CL[0-9][0-9][0-9]'),
	Cstock INT NOT NULL CHECK(Cstock BETWEEN 0 AND 250),
	Cprice INT NOT NULL,
	Cname VARCHAR(100) NOT NULL
);

CREATE TABLE [SalesTransactionDetail](
	STID CHAR(5) FOREIGN KEY REFERENCES [SalesTransactionHeader]([STID]) ON UPDATE CASCADE ON DELETE CASCADE,
	ClothSoldID CHAR(5) FOREIGN KEY REFERENCES [ClothSold]([ClothSoldID]) ON UPDATE CASCADE ON DELETE CASCADE,
	Quantity INT,
	PRIMARY KEY([STID], [ClothSoldID])
);
